# -*- coding: utf-8 -*-
"""teste

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f64grKLWFIDVpx5z8tMjy1LRcTQs8tba
"""

Indice = 13

Soma = 0

K = 0

while K < Indice:

   K = K + 1

   Soma = Soma + K

print (Soma)